#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

packer="sudo pacman -S --noconfirm --needed"

sudo $packer ttf-jetbrains-mono-nerd
sudo $packer arc-gtk-theme
sudo $packer papirus-icon-theme

THEME='arc-darc'
ICONS='Papirus-Dark'
FONT='JetBrainsMono Nerd Font 10'
CURSOR='Dracula-cursors'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
