#!/usr/bin/env bash

###
# Adapted form here
# https://github.com/miroslavvidovic/rofi-scripts
###

browser=google-chrome-stable

declare -A URLS

URLS=(
  ["Arch Wiki"]="https://wiki.archlinux.org/title/"
  ["Github"]="https://github.com/search?q="
  ["Gitlab"]="https://gitlab.com/search?q="
  ["Google"]="https://www.google.pl/search?q="
  ["Wikipedia"]="https://pl.wikipedia.org/w/index.php?search="
  ["YouTube"]="https://www.youtube.com/results?search_query="
)

# List for rofi
gen_list() {
    for i in "${!URLS[@]}"
    do
      echo "$i"
    done
}

main() {
  # Pass the list to rofi
  platform=$( (gen_list) | sort | tofi -c $HOME/.config/hypr/tofi/config  --prompt-text "Search > " )

  if [[ -n "$platform" ]]; then
    query=$( (echo ) | tofi -c $HOME/.config/hypr/tofi/config  --prompt-text "Query > " )

    if [[ -n "$query" ]]; then
      url=${URLS[$platform]}$query
      $browser "$url"
    else
      exit
    fi

  else
    exit
  fi
}

main

exit 0
