#!/bin/bash

CHOICE=`tofi -c ~/.config/hypr/tofi/config --prompt-text="  " << EOF

lock
reboot
poweroff
exit
EOF`

case $CHOICE in
  lock)
		$HOME/.config/hypr/scripts/offscreen
		;;
	reboot)
		systemctl "reboot"
		;;	
	poweroff)
		systemctl "poweroff"
		;;
	exit)
		loginctl "terminate-user" "$USER"
		;;
esac
