#!/bin/bash

cd ~/.config/hypr/configs/
chosen=$( ls | rofi -dmenu -i -p "  "  | awk '{print $1}' )
scripts=$chosen

# Exit if none chosen.                                                                         
[ -z "$chosen" ] && exit

fullpath=$(pwd)/$scripts;

kitty -e nvim $fullpath ;

