#!/bin/bash
#set -e

packer="sudo pacman -S --noconfirm --needed"

$packer dunst
$packer pdfarranger
$packer adobe-source-sans-fonts
$packer aic94xx-firmware
$packer alacritty
$packer arandr
$packer archiso
$packer avahi
$packer awesome-terminal-fonts
$packer baobab
$packer cpuid
$packer curl
$packer dconf-editor
$packer downgrade
$packer duf
$packer font-manager
$packer galculator
$packer gimp
$packer git
$packer gitahead-bin
$packer gitfiend
$packer gnome-disk-utility
$packer google-chrome
$packer gparted
$packer grub-customizer
$packer gtop
$packer gvfs-smb
$packer hardcode-fixer-git
$packer hardinfo-gtk3
$packer hddtemp
$packer htop
$packer hw-probe
$packer linux-firmware-qlogic
$packer logrotate
$packer lolcat
$packer lollypop
$packer lshw
$packer man-db
$packer man-pages
$packer mkinitcpio-firmware
$packer mlocate
$packer meld
$packer mintstick-git
$packer most
$packer neofetch
$packer networkmanager-openvpn
$packer noto-fonts
$packer ntp
$packer nss-mdns
$packer openresolv
$packer pavucontrol
$packer playerctl
$packer python-pylint
$packer python-pywal
$packer pv
$packer qbittorrent
$packer rate-mirrors-bin
$packer ripgrep
$packer rsync
$packer scrot
$packer sublime-text-4
$packer simplescreenrecorder
$packer sparklines-git
$packer speedtest-cli-git
$packer spotify
$packer starship
$packer squashfs-tools
$packer system-config-printer
$packer time
$packer tree
$packer ttf-bitstream-vera
$packer ttf-dejavu
$packer ttf-droid
$packer ttf-hack
$packer ttf-inconsolata
$packer ttf-liberation
$packer ttf-roboto
$packer ttf-roboto-mono
$packer ttf-ubuntu-font-family
$packer upd72020x-fw
$packer vlc
$packer wd719x-firmware
$packer wget
$packer wttr
$packer xcolor
$packer xorg-xkill
$packer libreoffice-fresh
$packer libreoffice-fresh-pl
sudo systemctl enable avahi-daemon.service
sudo systemctl enable ntpd.service
